### ISSUE TITLE
Some enhancement suggestions.

### ISSUE THREAD

**Issue by vascanera** [lbauskar/kanban#14]
Enhancement suggestions:
- Add a 'drag-move' icon (or something similar like three dots, etc.) to emphasize the idea that the area is draggable - I kept clicking on it, trying to edit the text 🤦🏻  - should be placed on the left side of the task-handle
- Add "Delete task? Yes/No" confirmation when deleting a task (to avoid accidental deletions)
- Vertical-align the "delete" icon on the task-handle bar
- Add a bit more padding to the inside of the task content (right now the content is a bit too close to the borders) - maybe, even make the task handle thinner (also makes accidental deletions less probable) and of a distinct color

Thanks for a great extension! Keep up the good work!

**Comment by lbauskar** [comment]
What do you mean by the 3 dots? I vaguely know what you're talking about, but I can't remember exactly what it looks like and don't know of anything that uses it off the top of my head.

**Comment by vascanera** [comment]
Actually, it's 6 dots, not 3... my bad. What I mean is something like these 3 icons (to emphasize the idea of a 'drag handle'):
![image](https://user-images.githubusercontent.com/45070144/155084647-7d39b53a-9e5b-45ca-bca7-2e65b1091022.png)

**Comment by lbauskar** [comment]
I added the leftmost gripper icon and aligned the icons in the task handle. Good eye on that one!

I have a couple more questions.

1.  How small is the task content on your screen? I don't have an issue clicking on them with my screen, but my monitors are only 1080 or 1440p. There might be something wonky going on with the screen or years of video games have made me blind to this issue.

2. I'm not too worried about accidental deletions because there's a history panel where you can review and undo every change you've made since you've last opened the board. Were you aware of this feature? If not, do you have any (non-intrusive) ideas for making that feature more apparent?

Sorry for taking a while to get to you. I had midterm season then completely tuned out of everything for spring break.
