### ISSUE TITLE
Enhancement: add possibility to specify path/filename for saving

### ISSUE THREAD

**Issue by vascanera** [lbauskar/kanban#15]
Please consider adding the option to select/specify a path/filename for saving data (maybe as a default option in exension's settings).
Lots of people/projects have .vscode ignored (in .gitignore). 
I would like to keep the saved kanban file in the root of the project, maybe in something like KANBAN.json, and be able to push changes to git (if .vscode directory is .gitignored) - this would be a neat feature.
Thank you!

**Comment by lbauskar** [comment]
One more thing.

I really don't want to overcomplicate this extension. I never want to get to the point where new users need a tutorial prompt or anything close to that. The reason I made this extension in the first place was because I wanted something quick and easy to use that had little to no learning curve. 

I also don't want to deprive people of the ability to use this program how they want to. Especially in this case, where it seems many people want some way to change the file name. I'm just asking that you keep in mind the balance between killer features and overall ease of use.

Also, if anyone else has suggestions regarding this issue, feel free to chime in.

**Comment by vascanera** [comment]
I think setting the name of the default file to KANBAN.json (and storing it in the root of the project along with other files like README.md & co.) would be a great addition. Most projects I've seen / used don't commit the .vscode folder (it is .gitignore'd), so, storing the file in the workspace is not very feasible for versioning. 
I'm all for simplicity and self-explanatory UIs, but having the possibility to version this file would be of great benefit, so if you could find a simple way to add this, it'd be a win! 
Keep up the good work!

**Comment by lbauskar** [comment]
In the 1.7 branch there's a new extension setting that let's you set valid filenames in descending priority. I couldn't find a simple-to-use solution that I was perfectly happy with, so I'm settling for a more complicated (but powerful) option hidden in the settings :/

**Comment by vfxturjo** [comment]
I want this feature too...

i think this will be good idea:
1. make the extension a handler for kanban files. so if one just clicks on the kanban file in the explorer, this extension will open and preview it
2. a way to make a kanban file "active", so it will be opened when we press the button in the bottom status bar in vscode (or simple open it in any way)
> 1.  so if someone wants to open another kanban file just to check it for once, he can do it.
> 2. this can be just a button on top, beside the "settings" button. click to set the current file as active.
3. If for some reason "active" kanban file is not found (moved/deleted) then opening the extension will show 1-time notification of something like: 
> `<active_kanban_filename> was not found. opening another kanban from default directory`
4. if everything looks complicated, then, these features will be set "disabled" by default, but users can go to settings and enable "multiple kanban handling, active kanbans" etc options... to get these features.


I'm requesting it because i tried many kanban extensions for vscode but yours is the most beautiful and responsive. the drag and drop feeling is so nice, and interface is simple and beautiful. <3
