### ISSUE TITLE
Feature Request: Add support for tasklist.

### ISSUE THREAD

**Issue by woogyface** [lbauskar/kanban#18]
As [react-markdown](https://github.com/remarkjs/react-markdown) does have support for plugins it would be pretty easy to add support for advanced markdown integration like tasklist:
```
* Lists
* [ ] todo
* [x] done
```
I'm not a react or vscode plugin specialist but as is see to make that happen is:
1. Add `remark-gfm` to [package.json](https://github.com/lbauskar/kanban/blob/2a1466d420d48813306ceaaa755cba40f8ad2b5d/package.json#L97)
2. Add `remark-gfm`as import to [task.tsx](https://github.com/lbauskar/kanban/blob/main/src/components/task.tsx)
3. Change in [task.tsx](https://github.com/lbauskar/kanban/blob/2a1466d420d48813306ceaaa755cba40f8ad2b5d/src/components/task.tsx#L70) lines 70-73 from
``` javascript
<ReactMarkdown>
    {data.text || '_enter text or markdown here_'}
</ReactMarkdown>
```
to
``` javascript
<ReactMarkdown remarkPlugin={[remarkGfm]}>
    {data.text || '_enter text or markdown here_'}
</ReactMarkdown>
```

How to integrate a plugin is descripted here: [react-markdown](https://github.com/remarkjs/react-markdown#use-a-plugin)

I have no experience in writing github issues so please exuse me if something not formatted right.

**Comment by lbauskar** [comment]
This issue is going on the backburner for now. By all accounts, your suggested change should work. The documentation for remark-gfm and react-markdown also specify that format. For whatever reason though, this crashes the extension when you try to edit the text.

I also would like to use task lists, so I _will_ get around to this. But debugging interactions between npm packages is not fun 🥴

**Comment by lbauskar** [comment]
`react-markdown` got an update which fixed the bug with `remark-gfm`! This feature is in 1.7
