### ISSUE TITLE
Enhancement: Better keyboard focus

### ISSUE THREAD

**Issue by Doctacosa** [lbauskar/kanban#20]
Nice extension! I've started playing around with it, and something light and straightforward is exactly what I was looking for. With that said, I have a few suggestions to improve its usability:

* Clicking on the + button to add a task should set keyboard focus on it so I can immediately start typing.
* Clicking on an existing item once should be enough to trigger editing mode, I don't see why I need to click twice.
* Pressing Ctrl+Enter on editing a note could finish the edition and display the rendered formatting without having to click somewhere else.
* After that Ctrl+Enter, maybe let people press Enter to resume editing that note (good for quick corrections).

**Comment by lbauskar** [comment]
Your suggestions are (mostly) feature complete in the  1.6 branch. There are just a couple remaining issues:

1. When a new task is made, it's in display mode for a split-second before switching to edit mode. This looks janky.
2. When focusing on a task, all of the text gets highlighted now. I'm okay with this behavior for `Ctrl`+`Enter`, but it's kind of weird when clicking on the task. I haven't found a native way to emulate the behavior of moving the caret to the cursor's position, and non-native ways I've thought up seem excessively intensive (computationally speaking) for such a simple UI action.

Anyway, I want to resolve those two issues before publishing these changes on the main branch.

**Comment by lbauskar** [comment]
Alright, the first issue is fixed.

As of right now I have no intention of changing the text-highlighting behavior from what I described previously. If [caretPositionFromPoint](https://docs.w3cub.com/dom/documentorshadowroot/caretpositionfrompoint.html) ever becomes a browser standard and works as expected, then I may use that. Otherwise, there's too much work (for the CPU) for me to justify changing the behavior without feeling gross about it.

**Comment by Doctacosa** [comment]
Thank you, much appreciated!
