### ISSUE TITLE
[FEATURE] Improve delete-column workflow

### ISSUE THREAD

**Issue by DarkTrick** [lbauskar/kanban#8]
**Currently** deleting a column via the trash is done *in the top*, the `undo` popup is *in the bottom* and shows only for a very short period of time.
**Suggestion:** put the `undo` overlay in the top (shorter cursor travel) and/or show it for a longer period of time (5 seconds? 10 seconds?)

**Currently** the icon for deleting a column is always visible. But I guess it's rarely used.
**Suggestion** Perhaps hide it inside a right-click-menu, that appears when column name is clicked.

**Comment by lbauskar** [comment]
I don't want to remove the `delete column` button because I don't find right clicking to show hidden options intuitive. Which leads me to believe there are others who don't find it intuitive either. The fact that intuition varies person to person is what makes UI design ~~difficult~~ interesting.

I think the real issue is with how `undo` works, and not with `delete column`. It shouldn't be attached to a timer, and you should be able to roll back more than one revision. Here's what I have planned for undoing. Let me know what you think.

![undo](https://user-images.githubusercontent.com/50561822/136529936-1dab5d58-1c9e-4fbe-b5f7-5516d8de40e2.png)

One thing not included in the mockup. Hovering over the history list element would show what the kanban board would look like if that element was clicked.
